name: get_time_ago
description: A Flutter package to convert and format `DateTime` object into `get_time_ago` format to get String like `10 seconds ago`, `a minute ago`, `7 hours ago`, etc.
version: 1.2.2
homepage: https://github.com/nixrajput
repository: https://github.com/nixrajput/get-time-ago
issue_tracker: https://github.com/nixrajput/get-time-ago/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.22.2
